name: Nsongwa Bank CI Audit

on: [push]

# HARDENING: Explicitly set minimum required permissions
permissions:
  contents: read

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Security Tools
        run: pip install checkov flask

      - name: Run Security Scan
        # Added --soft-fail for the demo if you want it to pass despite minor warnings
        run: checkov -d .

      - name: Test Docker Build
        run: docker build -t nsongwa-bank-test .
